### PR TITLE
Issue 425

### PR DESCRIPTION
**Pull request by Fraham**
### Description of the Change
Adds a new function for routes to get a list of all the configured routes on the server

### Related Issue
#425 

### Examples
Get-PodeRoutes

### CODE REVIEW

**Comment by Badgerati** [comment]
Hey @Fraham, just from what we spoke about earlier:

* Calling it `Get-PodeRoute` - make sure to rename the existing private function (maybe to `Find-PodeRoute` instead 🤔 and update references)
* Letting `Get-PodeRoute` return all routes, or be filtered by Route/Method

**Comment by Badgerati** [comment]
Merged with #486

**Comment by ArieHein** [comment]
Remember that you can now have multiple endpoints on same command as was added in 1.4.0 so i assume this will bring all of them across all endpoints ? with a note one what endpoint it belongs to ? parent-child like ?

**Comment by Badgerati** [comment]
The way routes in Pode are treated does mean if you add a `/` route on some `user` and `admin` endpoints then both will be returned as separate routes:

Assuming `user` is 127.0.0.1 and `admin` is 127.0.0.2, then calling `Get-PodeRoute` will return:
```powershell
@(
    @{
        Path = '/'
        EndpointNames = @('user', 'admin')
        Endpoint = 127.0.0.1
        # etc
    },
    @{
        Path = '/'
        EndpointNames = @('user', 'admin')
        Endpoint = 127.0.0.2
        # etc
    }
)
```

There is an `-Endpoint` and `-Protocol` filter currently on `Get-PodeRoute`, but I must admit I did miss an `-EndpointName` filter! I'll re-open #425 and add that in.

**Comment by ArieHein** [comment]
I usually use same IP but different ports

**Comment by Badgerati** [comment]
The Endpoint property is of the format `<ip>:<port>`, so you can pass `-Endpoint 127.0.0.1:8080` or `-Endpoint 127.0.0.1:8081` and the appropriate route will be returned - though it would be easier to be able to supply just the EndpointName.

**Pull request closed without merging**
